### ISSUE TITLE
URL of images not captured

### ISSUE THREAD

**Issue by lyndonlim27** [Wilsven/healthhub-content-optimization#126]
Article: https://www.healthhub.sg/a-z/costs-and-financing/chas
ID: 1435043

Images' URL like the different chas card were not capture
<img width="956" alt="image" src="https://github.com/user-attachments/assets/defeaf37-9292-4f05-9457-264b99757512">

**Comment by issacj-17** [comment]
@lyndonlim27 Thanks for raising this issue. I have resolved it. Awaiting approval of PR - https://trello.com/c/CX61LVIC/199-setup-of-gpt-4o-for-multi-modal-rag

**Comment by Wilsven** [comment]
Solved in #125.
