### ISSUE TITLE
Error running `kedro run` using windows

### ISSUE THREAD

**Issue by jwyting** [Wilsven/healthhub-content-optimization#42]
error running `kedro run` using windows. [Trello card](https://trello.com/c/eeuzuI1H)

Error:
[kedro.io](http://kedro.io/).core.DatasetError: Cannot save versioned dataset 'diseases-and-conditions\Diarrhoea in Children_ Causes, Symptoms and Treatments for Paediatric Diarrhoea.txt' to 'C:/Users/Joycelyn/Documents/Synapxe/07 GenAI for healthhub/Github/healthhub-content-optimization/content-optimization/data/02_intermediate/all_extracted_text' because a file with the same name already exists in the directory. This is likely because versioning was enabled on a dataset already saved previously. Either remove 'diseases-and-conditions\Diarrhoea in Children_ Causes, Symptoms and Treatments for Paediatric Diarrhoea.txt' from the directory or manually convert it into a versioned dataset by placing it in a versioned directory (e.g. with default versioning format 'C:/Users/Joycelyn/Documents/Synapxe/07 GenAI for healthhub/Github/healthhub-content-optimization/content-optimization/data/02_intermediate/all_extracted_text/diseases-and-conditions\Diarrhoea in Children Causes, Symptoms and Treatments for Paediatric [Diarrhoea.txt/YYYY-MM-DDThh.mm.ss.sssZ/diseases-and-conditions\Diarrhoea](http://diarrhoea.txt/YYYY-MM-DDThh.mm.ss.sssZ/diseases-and-conditions/Diarrhoea) in Children Causes, Symptoms and Treatments for Paediatric Diarrhoea.txt').

**Comment by Wilsven** [comment]
@issacj-17 Do resolve this issue as per what we have [discussed](https://trello.com/c/eeuzuI1H). Solution is to truncate title to first 10 characters and then append the unique ID as the new filename.

**Comment by Wilsven** [comment]
> @issacj-17 Do resolve this issue as per what we have [discussed](https://trello.com/c/eeuzuI1H). Solution is to truncate title to first 10 characters and then append the unique ID as the new filename. 

@issacj-17 Please refrain from working on this tonight. It's past working hours. Pick this up tomorrow. Have a good evening and rest! 😄😄

**Comment by issacj-17** [comment]
@Wilsven @jwyting Sure, I will do so. I am currently setting up the environment on my Windows machine. I will implement the changes and test for any errors/regression downstream on Windows. Once done, I will make a pull request to `kedro-branch`.

**Comment by issacj-17** [comment]
@Wilsven @jwyting @sixiannn I have resolved the bug for the filenames as per https://github.com/Wilsven/healthhub-content-optimization/pull/43. I have created a pull request to merge with `kedro-branch`.

Moving forward, I will need your help to monitor the quality of the extracted text. Please let me know if you have detected any degradation in the extracted texts during your experimentation e.g. missing text and duplicated text with an excerpt as well as the associated link on HealthHub.

**Comment by issacj-17** [comment]
Here is the information regarding the character limit for Windows File Path - https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by Wilsven** [comment]
@issacj-17 Do review my comments in #44 [here](https://github.com/Wilsven/healthhub-content-optimization/pull/44#discussion_r1655810862). Want to check if you mean to comment out a chunk of the function. If so, what's the reason? Was that not the change we included yesterday to deal with `<div>` content within `<div>` tags.

@jwyting @sixiannn Assigned you guys to the PR. Refer for more information [here](https://github.com/Wilsven/healthhub-content-optimization/pull/44#issuecomment-2192920203) at #44.

**Comment by jwyting** [comment]
Pipeline execution completed successfully on my windows machine.
