### ISSUE TITLE
Improve `extracted_links` and `extracted_headers`

### ISSUE THREAD

**Issue by Wilsven** [Wilsven/healthhub-content-optimization#48]
1. Extracted links included footnotes to references. Suggestion is to remove scraping footnotes as the links to the references aren't even present.

![image](https://github.com/Wilsven/healthhub-content-optimization/assets/64478824/d06de792-440c-46d5-845a-b2a1da02bd34)

![image](https://github.com/Wilsven/healthhub-content-optimization/assets/64478824/1c14fdb1-9e65-42f4-ac1b-8080e1c9ad8c)

2. Extracted headers also included the "References" headers which may not be relevant for downstream tasks. Suggestion is to remove. 

![image](https://github.com/Wilsven/healthhub-content-optimization/assets/64478824/e333a812-42a8-4e40-b8d4-0a8b5873af98)

**Comment by issacj-17** [comment]
I will remove the footnotes from the extracted_links, but I will keep the References in the extracted headers. 

This is my rationale for it -
 - Footnotes in links: Regarding modelling the relationships, the footnotes will contribute as much noise as they do not provide any unique information. 
- References in headers: Having it in References allows to either remove sections in articles with headers for embedding purposes or model relationships and test whether there are articles present that share the same references. This can be used to explain why the articles may be seen as similar.

Going forward, the first phase of the data processing pipeline will solely focus on preserving the original text as much as possible to facilitate various exploration approaches.

**Comment by Wilsven** [comment]
Resolved in PR #49

**Comment by Wilsven** [comment]
> I will remove the footnotes from the extracted_links, but I will keep the References in the extracted headers.
> 
> This is my rationale for it -
> 
> * Footnotes in links: Regarding modelling the relationships, the footnotes will contribute as much noise as they do not provide any unique information.
> * References in headers: Having it in References allows to either remove sections in articles with headers for embedding purposes or model relationships and test whether there are articles present that share the same references. This can be used to explain why the articles may be seen as similar.
> 
> Going forward, the first phase of the data processing pipeline will solely focus on preserving the original text as much as possible to facilitate various exploration approaches.

In hindsight, it is a good point that we may need to retain the "References" headers. However, since the changes have been integrated, we will refrain from making any more changes for now so as to avoid having many commits or PR for such a simple issue. Will reopen this issue for future discussion as well as reference!

**Comment by issacj-17** [comment]
Added back "References" headers in https://github.com/Wilsven/healthhub-content-optimization/pull/52/
