### ISSUE TITLE
Improve data cleaning for merged_data, pr_name column

### ISSUE THREAD

**Issue by jwyting** [Wilsven/healthhub-content-optimization#53]
To remove trailing white spaces behind values in pr_name column. 

Referring to below screenshot, there are values "Health Promotion Board" (count=32) and "Health Promotion Board " (count=956). For now, algorithm team can post-process this to extract data by HPB. Data pipeline team may look into correct this in the pipeline when merge_data.parquet file is generated. Thanks!

<img width="401" alt="image" src="https://github.com/Wilsven/healthhub-content-optimization/assets/139433726/7e19a4aa-a53f-4f02-a89e-f35ca43100ce">

**Comment by Wilsven** [comment]
Yup, we are aware of this issue but it slipped my mind yesterday when integrating my changes. Will integrate this fix into my next PR. For now, do work around this issue. Will notify once this is fixed. 

![image](https://github.com/Wilsven/healthhub-content-optimization/assets/64478824/8d1d2a50-6279-4222-a6b4-42c7e1c8e3e4)

**Comment by issacj-17** [comment]
@jwyting, I have made the changes in https://github.com/Wilsven/healthhub-content-optimization/pull/54. The addition is `df = df.map(lambda x: x.strip() if isinstance(x, str) else x)` in `nodes.py` file. Please run the new pipeline and let me know if there are no issues. Once done, I will close this issue.

**Comment by Wilsven** [comment]
@jwyting Please close this issue once everything is working.

**Comment by Wilsven** [comment]
@jwyting Everything good here? Do make sure to close the issue. Thanks!

**Comment by jwyting** [comment]
tested ok. thanks!
