### ISSUE TITLE
Improper rendering of article card on hover.

### ISSUE THREAD

**Issue by TsienJin** [Wilsven/healthhub-content-optimization#85]
Origin: #84

---

With reference to the Figma, the article "card" is not rendered properly. This is due to the lack of components from TUI library.

Currently, the "dropdown" directive is used to render this card, leading to the following problems:
- Cards rendered are blocking the rest of the list and should be rendered at the side of the article.
- Rendered content closes when user clicks on the "more" button on the top right.

Our own component/directives would be needed to render the "popover" card properly.

**Comment by Wilsven** [comment]
Is this something to note and not urgent or something to be resolved?

**Comment by TsienJin** [comment]
> Is this something to note and not urgent or something to be resolved?

Was to be fixed, but will not be fixed as UI requirements have changed
