### ISSUE TITLE
Feature Request: Flagging Pure Recipe Articles & Whitelisting Articles

### ISSUE THREAD

**Issue by issacj-17** [Wilsven/healthhub-content-optimization#89]
## TODO: 
- To discuss in greater detail how to handle recipe articles and where to include within the pipeline
- Recommend to flag articles back programmatically instead of individual whitelisting to improve pipeline resiliency

## Summary:
Here is the overview on handing articles flagged as `to_remove`:
- NaNs to be removed
- We will be given the content body for excel errors. To bring it back into the dataset somehow -> Need to see if parquet suffers from a similar limitation
- Remove those with no HTML tags
- Remove No extracted content from harmonisation
- Remove duplicated URLs that return 404
- For those below word count, it is a case by case basis

    - Recipe: The suggestion is to exclude but the requirement is to highlight all recipe articles
    - Bite-size reminders for parents: A question is posed on whether they can be harmonised with other content
    - Other content on parenting is seen as useful, but unsure how to handle text within images/infographics (i.e. can they be harmonised?)
---
- Refer to https://github.com/Wilsven/healthhub-content-optimization/pull/87#issuecomment-2220392501 for more information on the problem.

**Comment by issacj-17** [comment]
Refer to https://trello.com/c/V6Z7nKqh/117-feature-extraction-topics-modelling#comment-668f6bbfacbac2647ecb4d5c on proposal

**Comment by Wilsven** [comment]
I know we will be discussing in greater detail when I'm back on Monday. But how do you suggest we programmatically unflag the previously flagged articles? How would we know what kind of criteria or heuristics were used to determine if a "Below word count" article should be unflag? Do have a think about this before we reconnect again on Monday.

**Comment by issacj-17** [comment]
> I know we will be discussing in greater detail when I'm back on Monday. But how do you suggest we programmatically unflag the previously flagged articles? How would we know what kind of criteria or heuristics were used to determine if a "Below word count" article should be unflag? Do have a think about this before we reconnect again on Monday.

I think we should just add back articles under `Excel Error `together with the new content body (which we will be getting soon) and the rest of the articles under `below word count`. Those with excel errors can be whitelisted once the data has been successfully been captured. As for those under `below word count`, we do not have a way to programmatically sieve those without problems yet. So, our approaches downstream will need to be able to work with these types of articles.

**Comment by Wilsven** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review Excel provided by JingYi](https://trello.com/c/w9a1kB4x/146-review-excel-provided-by-jingyi)

**Comment by Wilsven** [comment]
## 1. Whitelisting Articles
As per Health Hub team's review, we have integrated the update to whitelist the articles provided in #103. Refer [here](https://docs.google.com/spreadsheets/d/1N39HV_LKo8bJ319uuFSCCrZrJEHfqoFb/edit?usp=sharing&ouid=107092437581450461344&rtpof=true&sd=true) for the full list of whitelisted articles. 

## 2. Flagging of Recipe Articles

![recipe_logic](https://github.com/user-attachments/assets/67ba1bad-bf02-4678-90b5-356d3fc9b6b1)

Implemented (but not integrated into pipeline) logic to flag articles as recipes. Pending Health Hub team's review. Refer to all articles flagged as recipes [here](https://docs.google.com/spreadsheets/d/1wMJYq4YwMBWXxiE8OlPFZwKaf1Y8XGH2/edit?usp=sharing&ouid=107092437581450461344&rtpof=true&sd=true). 

Further mentions in Trello: [Link](https://trello.com/c/w9a1kB4x)

**Comment by Wilsven** [comment]
@jzkoh @jwyting @sixiannn @issacj-17 

Please pull the new changes and re-run the Kedro pipeline. Below are the changes made to the respective `remove_type`s. Thanks all. I will be closing this issue.

## 1. `Excel Error`

- Added the content body of `Excel Error` back into dataset 
- See #101 

## 2. `Recipe`

- Integrated code to flag for recipe articles
- See #108
- Awaiting for Health Hub's review before **final** whitelisting of flagged recipes

## 3. `Multilingual`

- Added new flag for multilingual articles (i.e. Chinese, Malay and Tamil)
- See #109
